#!/usr/bin/env bash

# Autor: Microjus - Dark-Shell 
# Criaçao: 01/12/2021
# Script simples escrito em bash que calcula
# Adição, divisao, subtraçao 
# Multiplicaçao e raiz quadrada.

#------------------------------VARIAVEIS---------------------------------------|

declare -r ROOT_UID=0    # Somente usuários com $UID 0 têm privilégios de administrador.
declare -r NOT_ROOT=87   # Codigo de saida de erro para usuarios nao administrador.
declare -r NOT_FOUND=404 # Codigo de saida de erro para programa nao encontrado.

#-------------------------------TESTES-----------------------------------------|

# Verifica se o usiario é administrador do sistema.

[[ "$UID" -ne "$ROOT_UID" ]] && { printf "\033cE: Execute como adminstrador.\n" ; exit "$NOT_ROOT" ; }

#------------------------------------------------------------------------------|

trap ctrl_c INT

ctrl_c() {

        printf "\33c[+] (Ctrl + C ) Detectado, Tentativa de saida ...\n" ; sleep 2s
        printf "\n[+] Encerrando serviços , Aguarde  ...\n"
        # Funçao de encerramento
        printf "\n[+] Obrigado por usar este programa  =).\n"
        exit 1 
}

function menu() {
	
	clear ; echo '
	|-----------------------|
	|                       |
	|   MICRO CALCULATOR    |
	|                       |
	|-----------------------|
	
	[ 1 ] - Adição
	[ 2 ] - Divisão
	[ 3 ] - Subtração
	[ 4 ] - Multiplicação
	[ 5 ] - Raiz quadrada
	[ 0 ] - Sair
	'
	read -r -p '[+] Digite uma opção: ' opt
	
	case $opt in 
		
		1) adc ;;
		2) div ;;
		3) subtr ;;
		4) mult ;;
		5) raiz ;;
		0) enc ;;
		*)
		printf "\33c[+] Opção Invalida!" ; sleep 1 ; menu
		esac
}

function enc() {

	clear ; printf "\33c[+] Obrigado por usar este programa!" ; sleep 1s ; exit 0
}

function adc() {

	clear ; read -r -p '[+] Digite um numero: ' num1
	read -r -p '[+] Digite o numero a ser somado: ' num2
	
		adc=$(( $num1 + $num2 ))
	
	printf "\33c|  O resultado é: $adc  |\n"
	printf "\n Pressione ENTER:" ; read -s ; menu
}

function div() {

	clear ; read -r -p '[+] Digite um numero: ' num1
	read -r -p '[+] Digite outro numero: ' num2
	
		div=$(( $num1 / $num2 ))
	
	printf "\33c|  O resultado é: $div  |\n"
	printf "\n Pressione ENTER:" ; read -s ; menu
}

function subtr() {

	clear ; read -p "[+] Digite um numero: " num1
	read -p "[+] Digite um numero a ser subtraido: " num2
		
		subtr=$(( $num1 - $num2 ))
	
	printf "\33c|  O resultado é: $subtr  |\n"
	printf "\n Pressione ENTER:" ; read -s ; menu
}


function mult() {

	clear ; read -r -p '[+] Digite um numero: ' num1
	read -r -p '[+] Digite o numero a ser multiplicado: ' num2
	
		mult=$(( $num1 * $num2 ))
	
	printf "\33c|  O resultado é: $mult  |\n"
	printf "\n Pressione ENTER:" ; read -s ; menu
}

function raiz() {

	clear ; read -r -p '[+] Digite um numero: ' num1
	
		raiz=$(echo "$num1" | awk '{print sqrt($1)}')
 	
	printf "\33c|  A raiz quadrada de $num1 é: $raiz  |\n"
	printf "\nPressione ENTER:" ; read -s ; menu
}

menu
